const {gql} = require('apollo-server');

const typeDefs = gql`
	type Query {
		helloWorld: String
		allGames: JSON
		games(providers: [GameProviders], gameCollectionIds: [GameCollectionIds], cursor: String): Response
	}

	type Response {
		cursor: String
		data: JSON
	}

	enum GameProviders {
		BALLY
		BETSOFT
		COZY
		EVOLUTION
		IGT
		KAMBI
		MERKUR
		MICRO
		NETENT
		NETENTLIVECASINO
		NOLIMITCITY
		ODOBO
		OGS
		PLAYNGO
		PLAYTECH
		QUICKSPIN
		REDTIGER
		SCIENTIFIC
		YGGDRASIL
	}

	enum GameCollectionIds {
		ALL_GAMES_A_Z
		ALL_TABLES_LIVE
		ALLGAMES
		APPLE_DROP
		BACCARAT_LIVE
		BEST_JACKPOTS
		BLACKJACK_LIVE
		BYGONES_BIGONES
		CASCADING_WILDS_1
		CASCADING_WILDS_2
		CASH_YEAR
		CASH_YEAR_CA
		CASH_YEAR_DK
		CASINO_REACTIVATION
		CHRISTMAS_01
		CHRISTMAS_02
		CHRISTMAS_03
		CHRISTMAS_04
		CHRISTMAS_05
		CHRISTMAS_07
		CHRISTMAS_08
		CHRISTMAS_09
		CHRISTMAS_10
		CHRISTMAS_11
		CHRISTMAS_12
		CHRISTMAS_13
		CHRISTMAS_14
		CHRISTMAS_15
		CHRISTMAS_16
		CHRISTMAS_17
		CHRISTMAS_18
		CHRISTMAS_19
		CHRISTMAS_20
		CHRISTMAS_21
		CHRISTMAS_22
		CHRISTMAS_23
		CHRISTMAS_24
		CHRISTMAS_25
		CHRISTMAS_26
		CHRISTMAS_CALENDAR
		CHRISTMAS_HERO
		CLUB_ROYALE_CHRISTMAS_BLACKJACK
		CLUB_ROYALE_CHRISTMAS_LIVE
		CLUB_ROYALE_HAPPY_HOURS
		CLUB_ROYALE_LIVE
		CLUB_ROYALE_MACAU
		CR_BLACKJACK
		CUP_1
		CUP_2
		CUP_3
		DACH_YGG_11
		EGYPT_VS_VIKINGS
		EXTREME_GOLDEN_ACES
		FAIRYTALE_PARTY
		FLY_HIGH_1
		FLY_HIGH_2
		FREE_SPIN_GENERATOR
		FREESPINS IN SPRING
		GADGET_DROP
		GLOBAL_MUSIC_FESTIVAL
		GOLD_CARD
		GOLDEN
		GREEN_ROOM
		GUARDIANS_OF_ASGARD
		HALLOWEEN_LIVE_BOOST
		HAPPY_HOUR
		HAPPY_HOURS
		HIGH_FREQUENCY_1
		HIGH_FREQUENCY_2
		HOT_JACKPOTS
		JACKPOT
		LIGHTNING_CAMPAIGN
		LIVE
		LIVE_BEYOND_LIVE_FREESPINS
		LIVE_EXTREME_MATCH
		LIVE_JACKPOT
		LUCKY_21
		LUCKY_SYMBOLS
		MRG
		MRGREEN
		MY_FREE_SPIN_ADVENTURE
		NETENT_MONEY_MAKER_PROMO
		NEW_YEAR_NEW_YORK
		NEWGAMES
		PARTY_PRIZE_DRAW
		POKER_LIVE
		PRIMATE_PLAYTIME
		PYRAMID_PROMOTION
		REWARD_FS
		ROULETTE_LIVE
		SANTA_WORKSHOP
		SENIOR_JOURNEY
		SLOTS
		SUNDANCE_KID
		SUPER_ROULETTE
		SUPER_ROULETTE_CLASH
		TABLE_GAMES
		TEST_CATEGORY
		TEST_PILOT
		THE_PARTY_COLLECTION
		TOP_RATED
		TOP_RATED_LIVE
		VIKING_COLLECTION
		VIP_COLLECTION
		WELCOME_OFFER
		WELCOME_OFFER_2
		WIN_CAR_YGGDRASIL
		WORLD_JACKPOT
		WORLD_OF_WONDER
		YGGDRASIL_CHRISTMAS
		YGGDRASIL_CHRISTMAS_01
		YGGDRASIL_CHRISTMAS_02
		YGGDRASIL_CHRISTMAS_03
		YGGDRASIL_CHRISTMAS_04
		YGGDRASIL_CHRISTMAS_05
		YGGDRASIL_CHRISTMAS_06
		YGGDRASIL_CHRISTMAS_07
		YGGDRASIL_CHRISTMAS_08
	}

  scalar JSON
`;

module.exports = typeDefs;